Update the user-agents
mozilla-services/contile-loadtests pull request #15
Opened 2021-08-30 19:56 UTC by ashrivastava-qa

## Description

Updated the user agents for the tests.

## Issue(s)

Closes #14

2021-08-31 13:35 UTC, hackebrot reviewed
Hi @ashrivastava-qa! 👋🏻 

Did you verify these new `User-Agent` header values to see if Contile handles them as expected?

2021-09-01 19:42 UTC, ashrivastava-qa commented
Hi @hackebrot, I tested these header values in the Woothee's demo site : `http://woothee.github.io/` and Contile uses the same library (Woothee) for parsing the User-Agent Header. So Contile will be able to handle them.

2021-09-02 07:48 UTC, hackebrot requested changes

2021-09-02 07:48 UTC, hackebrot commented on loadtest.py
> +    'Mozilla/5.0 (X11; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/91.0',
I suggest we have at least one `User-Agent` for Firefox 90 to test for legacy image handling:

```suggestion
    'Mozilla/5.0 (X11; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0',
```

2021-09-02 13:05 UTC, ashrivastava-qa commented
Yes that's a good idea, committed the suggestion. Thanks!

2021-09-02 13:20 UTC, hackebrot approved these changes
LGTM! Thanks @ashrivastava-qa! 👍🏻

2021-09-02 13:24 UTC, merged

2021-09-02 13:29 UTC, ashrivastava-qa commented
@pjenvey I merged the PR before seeing that Raphael requested a review from you. I'd very much like for you to review it still and let me know if the changes looks good to you. Thanks!